//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxml_salesorder_header
    {
        public string CompanyID { get; set; }
        public string WarehouseID { get; set; }
        public long OrderNo { get; set; }
        public string CustID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string InvDesc { get; set; }
        public string InvAddress1 { get; set; }
        public string InvAddress2 { get; set; }
        public string InvAddress3 { get; set; }
        public string InvCity { get; set; }
        public string InvTown { get; set; }
        public string InvPostCode { get; set; }
        public string InvCountry { get; set; }
        public string DelDesc { get; set; }
        public string DelAddress1 { get; set; }
        public string DelAddress2 { get; set; }
        public string DelAddress3 { get; set; }
        public string DelCity { get; set; }
        public string DelTown { get; set; }
        public string DelPostCode { get; set; }
        public string DelCountry { get; set; }
        public string CustRef { get; set; }
        public string ContractRef { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string Carrier { get; set; }
        public Nullable<decimal> CarrierCharge { get; set; }
        public Nullable<double> CustDisc { get; set; }
        public Nullable<double> SettDisc { get; set; }
        public Nullable<double> VolDisc { get; set; }
        public Nullable<int> SettlementDays { get; set; }
        public Nullable<byte> OrderConfirm { get; set; }
        public string CommentsExternal { get; set; }
        public Nullable<sbyte> Cancelled { get; set; }
        public Nullable<sbyte> ProForma { get; set; }
        public Nullable<sbyte> Completed { get; set; }
        public Nullable<double> WorksOrderNo { get; set; }
        public Nullable<sbyte> AllowPartShipment { get; set; }
        public Nullable<double> TotalGoods { get; set; }
        public Nullable<double> OrderGoods { get; set; }
        public string UserID { get; set; }
        public Nullable<sbyte> pRINTINVOICE { get; set; }
        public Nullable<double> Currency_Exchange_Rate { get; set; }
        public string PinNo { get; set; }
        public string UCodeId { get; set; }
        public string ContractNo { get; set; }
        public string Currency_Exchange_Code { get; set; }
        public Nullable<System.TimeSpan> TIMEOFENTRY { get; set; }
        public Nullable<long> RepID { get; set; }
        public Nullable<long> RepNo { get; set; }
        public Nullable<sbyte> OnlineConfirm { get; set; }
        public Nullable<System.DateTime> OnlineConfirmDate { get; set; }
        public string OnlineConfirmedBy { get; set; }
        public Nullable<sbyte> OnlineProcessed { get; set; }
        public Nullable<System.DateTime> OnlineProcessedDate { get; set; }
        public string OnlineProcessedBy { get; set; }
        public Nullable<int> ReasonCode { get; set; }
        public string OnlineUserID { get; set; }
        public string OrderAnalysisCode1 { get; set; }
        public string OrderAnalysisCode2 { get; set; }
        public string OrderAnalysisCode3 { get; set; }
        public string OrderAnalysisCode4 { get; set; }
        public string OrderAnalysisCode5 { get; set; }
        public string ordertype { get; set; }
    }
}
