//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_cordant_address
    {
        public string Companyid { get; set; }
        public string Businessid { get; set; }
        public int OldAddressid { get; set; }
        public Nullable<int> NewAddressid { get; set; }
        public Nullable<int> Contactid { get; set; }
        public Nullable<int> NewContactId { get; set; }
    }
}
