//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_demo_pickslips
    {
        public string CustID { get; set; }
        public string PinNo { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<long> NewOrderNo { get; set; }
        public int PickingSlipNo { get; set; }
        public Nullable<long> NewPickSlipNo { get; set; }
    }
}
