//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_employee_to_branch
    {
        public string COMPANYID { get; set; }
        public string busineSSID { get; set; }
        public string OnlineUserID { get; set; }
        public string Employeeid { get; set; }
    }
}
