//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_emplo_ve
    {
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string BUSINESSID { get; set; }
        public Nullable<decimal> COUNTID { get; set; }
    }
}
