//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_pwc_locations
    {
        public string styleid { get; set; }
        public string colourid { get; set; }
        public string sizeid { get; set; }
        public Nullable<int> Qty { get; set; }
    }
}
