//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_price_update
    {
        public int InvoiceNo { get; set; }
        public int Lineno { get; set; }
        public int salesorderno { get; set; }
        public int SOLineno { get; set; }
        public int PickingSLipno { get; set; }
        public int PSlineno { get; set; }
        public string Styleid { get; set; }
        public Nullable<decimal> Oldprice { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
    }
}
