//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_s27_rollout_order_delete
    {
        public string CompanyID { get; set; }
        public int OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string CustRef { get; set; }
    }
}
