//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_s27_order_adjust
    {
        public long OrderNo { get; set; }
        public Nullable<decimal> TotalGoods { get; set; }
        public Nullable<decimal> OrderGoods { get; set; }
    }
}
