//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_tsb_min_orderdate
    {
        public string CompanyID { get; set; }
        public string CustID { get; set; }
        public string Pinno { get; set; }
        public Nullable<System.DateTime> Min_OrderDate_ { get; set; }
    }
}
