//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_tsb_new_delday
    {
        public string BusinessID { get; set; }
        public int AddressID { get; set; }
        public string Description { get; set; }
        public string Postcode { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string Name { get; set; }
        public string CurrentDay { get; set; }
        public Nullable<int> NewDay { get; set; }
    }
}
