//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_tremot02
    {
        public int OrderNo { get; set; }
        public string CompanyID { get; set; }
        public string WarehouseID { get; set; }
        public string BusinessID { get; set; }
        public string Pinno { get; set; }
        public string Style1 { get; set; }
        public string Colour1 { get; set; }
        public string Size1 { get; set; }
        public string Qty1 { get; set; }
        public string Style2 { get; set; }
        public string Colour2 { get; set; }
        public string Size2 { get; set; }
        public string Qty2 { get; set; }
    }
}
