//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_tsbban01_partner_convert
    {
        public string BusinessID { get; set; }
        public string OnlineUserID { get; set; }
        public string BranchForename { get; set; }
        public string BranchSurname { get; set; }
        public string Email_ID { get; set; }
        public string EmployeeID { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public sbyte EmployeeClosed { get; set; }
        public string AccessID { get; set; }
        public string NewPartnerID { get; set; }
    }
}
