//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_visexp01_dimfit_style
    {
        public string UcodeID { get; set; }
        public string DimFitStyle { get; set; }
        public string UcodeStyleID { get; set; }
    }
}
