//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ht_tsb_2020_custref_change
    {
        public int OrderNo { get; set; }
        public string Current_Ref { get; set; }
        public string Change_Ref { get; set; }
    }
}
