//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stylebytemplateview
    {
        public string CompanyID { get; set; }
        public string StyleID { get; set; }
        public string StyleImage { get; set; }
        public Nullable<int> Product_Group { get; set; }
        public string Template { get; set; }
        public string BusinessID { get; set; }
        public string FreeText { get; set; }
    }
}
