//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblaccemp_rollout_email
    {
        public int Id { get; set; }
        public string CompanyId { get; set; }
        public string BusinessId { get; set; }
        public string EmployeeId { get; set; }
        public string Emailid { get; set; }
        public string RolloutName { get; set; }
        public Nullable<System.DateTime> NextOrderDate { get; set; }
        public Nullable<System.DateTime> MailSenton { get; set; }
        public string IsMailSent { get; set; }
    }
}
