//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblaccemp_employee_rollout
    {
        public string CompanyID { get; set; }
        public string BusinessID { get; set; }
        public string EmployeeID { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<int> PrevOrder { get; set; }
        public string RolloutName { get; set; }
    }
}
