//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblaccemp_ucodes_hours
    {
        public string CompanyID { get; set; }
        public float FromHour { get; set; }
        public float ToHour { get; set; }
        public string Gender { get; set; }
        public string BusinessID { get; set; }
        public string UCodeID { get; set; }
    }
}
