//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblaccemp_style_staticqty
    {
        public string CompanyID { get; set; }
        public string BusinessID { get; set; }
        public string StyleID { get; set; }
        public string ColourID { get; set; }
        public Nullable<int> StaticQty { get; set; }
        public byte[] StyleTypeID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string RolloutName { get; set; }
        public Nullable<int> ID { get; set; }
    }
}
