//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblaccemp_employee_atlasfm
    {
        public string CompanyID { get; set; }
        public string EmployeeID { get; set; }
        public string BusinessID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string Title { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public sbyte EmployeeClosed { get; set; }
        public Nullable<int> roleid { get; set; }
        public sbyte IsDefault { get; set; }
    }
}
