//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblaccemp_ucode_alternates
    {
        public string CompanyId { get; set; }
        public string BusinessId { get; set; }
        public string UcodeId { get; set; }
        public string StyleId { get; set; }
        public string ColourId { get; set; }
        public string SizeId { get; set; }
        public string AltStyleId { get; set; }
        public string AltColourId { get; set; }
        public string AltSizeId { get; set; }
        public Nullable<bool> IsHidden { get; set; }
    }
}
