//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblchildmenu_newlayout
    {
        public int ParentID { get; set; }
        public string ChildID { get; set; }
        public string Description { get; set; }
        public Nullable<sbyte> IsEnable { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public string URL { get; set; }
        public string TitleDesc { get; set; }
        public Nullable<sbyte> IsPopUp { get; set; }
        public Nullable<sbyte> OnlyNewLayout { get; set; }
    }
}
