//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfsk_unitofmeasure
    {
        public string CompanyID { get; set; }
        public int UnitID { get; set; }
        public string UnitShortCode { get; set; }
        public string UnitDescription { get; set; }
        public Nullable<int> Seqno { get; set; }
    }
}
