//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfsk_style_colour_size
    {
        public string CompanyID { get; set; }
        public string Warehouseid { get; set; }
        public string DefaultLocationId { get; set; }
        public string StyleID { get; set; }
        public string ColourID { get; set; }
        public string SizeID { get; set; }
        public Nullable<int> soldqtyper { get; set; }
        public Nullable<int> soldvalper { get; set; }
        public Nullable<int> soldqtyytd { get; set; }
        public Nullable<int> soldvalytd { get; set; }
        public Nullable<decimal> costvalper { get; set; }
        public Nullable<decimal> costvalytd { get; set; }
    }
}
