//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfsk_style_gallery
    {
        public int ID { get; set; }
        public string StyleID { get; set; }
        public string StyleImage { get; set; }
        public Nullable<bool> Is360 { get; set; }
        public Nullable<int> NoFrames { get; set; }
        public Nullable<int> NoFootages { get; set; }
    }
}
