//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfstk_feature
    {
        public string FeatureId { get; set; }
        public string CompanyID { get; set; }
        public string StyleID { get; set; }
        public string Description { get; set; }
        public bool flgPurchaseOrder { get; set; }
        public Nullable<int> QtyPerStyle { get; set; }
    }
}
