//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfskstyle_dimension1
    {
        public string CompanyId { get; set; }
        public string FreeText { get; set; }
        public string StyleId { get; set; }
        public string freetexttype { get; set; }
        public string StyleImage { get; set; }
        public string Description { get; set; }
    }
}
