//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblgen_user_parameters_copy
    {
        public string ParamID { get; set; }
        public string Param_Name { get; set; }
        public string Default_Value { get; set; }
        public string Lookup_SQL { get; set; }
    }
}
