//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblgen_parameters
    {
        public string ParamID { get; set; }
        public string Category { get; set; }
        public string Caption { get; set; }
        public string Input_Mask { get; set; }
        public string ModuleID { get; set; }
        public string DefaultValue { get; set; }
        public string Lookup_Table { get; set; }
        public Nullable<int> SeqNo { get; set; }
    }
}
