//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblgen_autonumbers
    {
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public Nullable<long> AutoNumber { get; set; }
        public string Locked { get; set; }
        public string CompanyID { get; set; }
    }
}
