//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblonline_rolloutorders_reqstatus
    {
        public string CompanyID { get; set; }
        public int OrderNo { get; set; }
        public Nullable<int> IsReq { get; set; }
    }
}
