//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpermission_users_deny
    {
        public string CompanyID { get; set; }
        public string UserID { get; set; }
        public string BusinessID { get; set; }
        public string DenyUser { get; set; }
    }
}
