//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsop_pickingslip_header
    {
        public string CompanyID { get; set; }
        public string WarehouseId { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public int PickingSlipNo { get; set; }
        public string CustID { get; set; }
        public Nullable<System.DateTime> DateAllocated { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public sbyte Printed { get; set; }
        public sbyte DelNoteFlag { get; set; }
        public sbyte ProForma { get; set; }
        public string UserID { get; set; }
        public Nullable<double> Currency_Exchange_Rate { get; set; }
        public string PinNo { get; set; }
        public string UCodeId { get; set; }
        public string ContractNo { get; set; }
        public sbyte FlagInvoice { get; set; }
        public string CustRef { get; set; }
        public sbyte Cancelled { get; set; }
        public sbyte DelPrinted { get; set; }
        public Nullable<int> RepID { get; set; }
        public Nullable<int> PackingNoteNo { get; set; }
        public Nullable<System.DateTime> PackingDate { get; set; }
        public string UserID_Packing { get; set; }
        public sbyte IsBackOrder { get; set; }
    }
}
