//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsop_salesorder_approved
    {
        public string CompanyID { get; set; }
        public long OrderNo { get; set; }
        public string OrderEnteredBy { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<System.TimeSpan> ApprovedAt { get; set; }
        public Nullable<bool> Approved { get; set; }
    }
}
