//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsop_return_credited
    {
        public string CompanyId { get; set; }
        public string BusinessId { get; set; }
        public int OrderNo { get; set; }
        public System.DateTime CreditedDate { get; set; }
        public string UserId { get; set; }
        public string EmployeeId { get; set; }
        public int TotalPoints { get; set; }
    }
}
