//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsop_salesorder_header_offline
    {
        public string CompanyID { get; set; }
        public string WarehouseID { get; set; }
        public int OrderNo { get; set; }
        public string CustID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string InvDesc { get; set; }
        public string InvAddress1 { get; set; }
        public string InvAddress2 { get; set; }
        public string InvAddress3 { get; set; }
        public string InvCity { get; set; }
        public string InvTown { get; set; }
        public string InvPostCode { get; set; }
        public string InvCountry { get; set; }
        public string DelDesc { get; set; }
        public string DelAddress1 { get; set; }
        public string DelAddress2 { get; set; }
        public string DelAddress3 { get; set; }
        public string DelCity { get; set; }
        public string DelTown { get; set; }
        public string DelPostCode { get; set; }
        public string DelCountry { get; set; }
        public string CustRef { get; set; }
        public string ContractRef { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string Carrier { get; set; }
        public Nullable<decimal> CarrierCharge { get; set; }
        public Nullable<double> CustDisc { get; set; }
        public Nullable<double> SettDisc { get; set; }
        public Nullable<double> VolDisc { get; set; }
        public Nullable<short> SettlementDays { get; set; }
        public sbyte OrderConfirm { get; set; }
        public string CommentsExternal { get; set; }
        public sbyte Cancelled { get; set; }
        public sbyte ProForma { get; set; }
        public sbyte Completed { get; set; }
        public Nullable<double> WorksOrderNo { get; set; }
        public sbyte AllowPartShipment { get; set; }
        public Nullable<double> TotalGoods { get; set; }
        public Nullable<double> OrderGoods { get; set; }
        public string UserID { get; set; }
        public sbyte pRINTINVOICE { get; set; }
        public Nullable<double> Currency_Exchange_Rate { get; set; }
        public string PinNo { get; set; }
        public string UCodeId { get; set; }
        public string ContractNo { get; set; }
        public string Currency_Exchange_Code { get; set; }
        public Nullable<System.TimeSpan> TIMEOFENTRY { get; set; }
        public Nullable<int> RepID { get; set; }
        public Nullable<int> RepNo { get; set; }
        public Nullable<int> ReasonCode { get; set; }
        public string OnlineUserID { get; set; }
        public string OrderAnalysisCode1 { get; set; }
        public string OrderAnalysisCode2 { get; set; }
        public string OrderAnalysisCode3 { get; set; }
        public string OrderAnalysisCode4 { get; set; }
        public string OrderAnalysisCode5 { get; set; }
        public sbyte PrintLabel { get; set; }
        public sbyte ProFormaPrint { get; set; }
        public sbyte ConfirmPrint { get; set; }
        public string OrderAnalysisCode6 { get; set; }
        public string OrderAnalysisCode7 { get; set; }
        public string OrderAnalysisCode8 { get; set; }
        public string OrderAnalysisCode9 { get; set; }
        public string OrderAnalysisCode10 { get; set; }
        public string OrderType { get; set; }
        public Nullable<sbyte> IsStockMove { get; set; }
        public string EmailID { get; set; }
        public string ContactName { get; set; }
    }
}
