//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsop_customerorder_template
    {
        public string CompanyID { get; set; }
        public string BusinessID { get; set; }
        public string Template { get; set; }
        public short LineNo { get; set; }
        public string Style { get; set; }
        public string Colour { get; set; }
        public string SizeiD { get; set; }
        public Nullable<int> SeqNo { get; set; }
    }
}
