//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsop_pickingslip_detail
    {
        public string CompanyID { get; set; }
        public string WarehouseId { get; set; }
        public int PickingSlipNo { get; set; }
        public int LineNo { get; set; }
        public Nullable<short> LineType { get; set; }
        public string LocationId { get; set; }
        public string StyleID { get; set; }
        public string Description { get; set; }
        public string ColourID { get; set; }
        public string SizeID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> OrdQty { get; set; }
        public Nullable<int> AllQty { get; set; }
        public Nullable<int> InvQty { get; set; }
        public Nullable<int> DespQty { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<double> CommissionRate { get; set; }
        public Nullable<double> Discount { get; set; }
        public sbyte StockProblem { get; set; }
        public Nullable<System.DateTime> FinalisedDeliveryDate { get; set; }
        public Nullable<double> Currency_Exchange_Rate { get; set; }
        public string StyleIDref { get; set; }
        public Nullable<int> Rep { get; set; }
        public Nullable<int> Kam { get; set; }
        public Nullable<double> RecNo { get; set; }
        public Nullable<double> DiscountPer { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> RepID { get; set; }
        public Nullable<double> RepRate { get; set; }
        public Nullable<int> KamID { get; set; }
        public Nullable<double> KamRate { get; set; }
        public Nullable<short> SOLineNo { get; set; }
        public Nullable<int> IssueUOM { get; set; }
        public Nullable<double> IssueQty { get; set; }
        public Nullable<int> StockingUOM { get; set; }
        public Nullable<int> OriginalPickingSlipNo { get; set; }
        public Nullable<int> OriginalPSLineNo { get; set; }
        public Nullable<System.DateTime> Rec_Date { get; set; }
        public Nullable<System.DateTime> CreatedDateTIme { get; set; }
        public Nullable<short> StatusMode { get; set; }
        public string UserData1 { get; set; }
        public string UserData2 { get; set; }
        public string UserData3 { get; set; }
        public string UserData4 { get; set; }
        public string UserData5 { get; set; }
        public Nullable<int> ReasonCode { get; set; }
    }
}
