//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsop_invoice_header
    {
        public string CompanyID { get; set; }
        public string WarehouseId { get; set; }
        public int InvoiceNo { get; set; }
        public sbyte Printed { get; set; }
        public sbyte Posted { get; set; }
        public string CustID { get; set; }
        public string CustomerOrder { get; set; }
        public string InvDesc { get; set; }
        public string InvAddress1 { get; set; }
        public string InvAddress2 { get; set; }
        public string InvAddress3 { get; set; }
        public string InvCity { get; set; }
        public string InvTown { get; set; }
        public string InvPostCode { get; set; }
        public string InvCountry { get; set; }
        public string DelDesc { get; set; }
        public string DelAddress1 { get; set; }
        public string DelAddress2 { get; set; }
        public string DelAddress3 { get; set; }
        public string DelCity { get; set; }
        public string DelTown { get; set; }
        public string DelPostCode { get; set; }
        public string DelCountry { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> Goods { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<double> CustDisc { get; set; }
        public Nullable<decimal> CustDiscAmount { get; set; }
        public Nullable<double> CashDays1 { get; set; }
        public Nullable<double> CashDisc1 { get; set; }
        public Nullable<decimal> SettDiscAmount { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string InvoiceCredit { get; set; }
        public string Purchase_Order_No { get; set; }
        public Nullable<int> No_of_Cartons { get; set; }
        public Nullable<short> Carrier_No { get; set; }
        public string Carrier_Name { get; set; }
        public Nullable<decimal> Carrier_Charge { get; set; }
        public Nullable<int> Carr_Nominal { get; set; }
        public Nullable<short> Carr_Vat_Code { get; set; }
        public Nullable<System.DateTime> Despatch_Date { get; set; }
        public string CustRef { get; set; }
        public string ContractRef { get; set; }
        public string Comments { get; set; }
        public Nullable<int> SalesOrderID { get; set; }
        public Nullable<int> RepCode { get; set; }
        public Nullable<int> PickingSlipNo { get; set; }
        public Nullable<decimal> CommissionValue { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> KAMRate { get; set; }
        public Nullable<double> KAMID { get; set; }
        public Nullable<short> CalendarPeriod { get; set; }
        public string ReasonForCredit { get; set; }
        public string PinNo { get; set; }
        public string UCodeId { get; set; }
        public string ContractNo { get; set; }
        public Nullable<int> Invoice_Type { get; set; }
        public string Invoice_Text { get; set; }
        public string Entry_Type { get; set; }
        public string UserID { get; set; }
        public string CommentsExternal { get; set; }
        public sbyte IsExtract { get; set; }
    }
}
