//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsop_carrier
    {
        public string CarrierID { get; set; }
        public string Name { get; set; }
        public Nullable<double> StandardRate { get; set; }
        public Nullable<int> NominalCode { get; set; }
        public string CompanyID { get; set; }
        public string Couriername { get; set; }
        public Nullable<int> Prefix { get; set; }
        public Nullable<int> Suffix { get; set; }
        public string Custlen { get; set; }
        public string Courier_CustomerId { get; set; }
    }
}
