//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsop_invoice_detail
    {
        public string CompanyID { get; set; }
        public string WarehouseId { get; set; }
        public int InvoiceNo { get; set; }
        public short LineNo { get; set; }
        public Nullable<short> LineType { get; set; }
        public string LocationId { get; set; }
        public string Style { get; set; }
        public string Colour { get; set; }
        public string Size { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> GoodsAmount { get; set; }
        public Nullable<short> VatCode { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<short> NomCode { get; set; }
        public Nullable<decimal> CustDiscLineAmount { get; set; }
        public Nullable<decimal> GoodsMinusCD { get; set; }
        public Nullable<decimal> SettDiscLineAmount { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> DecimalQty { get; set; }
        public string CommodityCode { get; set; }
        public Nullable<int> PickingSlipNo { get; set; }
        public Nullable<int> SalesOrder { get; set; }
        public Nullable<int> RepKey { get; set; }
        public Nullable<int> KAMKey { get; set; }
        public string StyleIdRef { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> RepID { get; set; }
        public Nullable<double> RepRate { get; set; }
        public Nullable<int> KamID { get; set; }
        public Nullable<double> KamRate { get; set; }
        public Nullable<int> PSLineNo { get; set; }
        public Nullable<int> SOLineNo { get; set; }
        public Nullable<double> Rec_No { get; set; }
        public Nullable<System.DateTime> Rec_date { get; set; }
        public string FreeText { get; set; }
        public Nullable<int> IssueUOM { get; set; }
        public Nullable<double> IssueQty { get; set; }
        public Nullable<int> StockingUOM { get; set; }
        public Nullable<int> OriginalPickingSlipNo { get; set; }
        public Nullable<int> OriginalPSLineNo { get; set; }
        public Nullable<double> CommissionRate { get; set; }
        public Nullable<int> OriginalPO { get; set; }
        public Nullable<int> OriginalPOLine { get; set; }
    }
}
