//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluser
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ForeName { get; set; }
        public string SurName { get; set; }
        public string ContactNo { get; set; }
        public string AccessID { get; set; }
        public string Active { get; set; }
        public string BusinessID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string LastIPAddress { get; set; }
        public Nullable<System.DateTime> LastLoggedDate { get; set; }
        public string Createdby { get; set; }
        public string Email_ID { get; set; }
        public string AspUserID { get; set; }
        public string BusinessName { get; set; }
    }
}
