//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unrelatedorder
    {
        public long OrderNo { get; set; }
        public string CustID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string PinNo { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string UCodeId { get; set; }
        public string StyleID { get; set; }
        public Nullable<long> OrdQty { get; set; }
    }
}
