//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Data.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ucode_freetext_tsb_rollout
    {
        public string UCodeID { get; set; }
        public string FreeText { get; set; }
        public Nullable<decimal> AnnualIssue { get; set; }
    }
}
