//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dim_fit_styles
    {
        public string CompanyID { get; set; }
        public string WareHouseID { get; set; }
        public string FreeTextType { get; set; }
        public string FreeText { get; set; }
        public string StyleIDs { get; set; }
    }
}
