//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class getproductslist
    {
        public string CompanyID { get; set; }
        public string StyleID { get; set; }
        public string Description { get; set; }
        public string StyleImage { get; set; }
        public string ColourID { get; set; }
        public string SizeID { get; set; }
        public Nullable<short> SeqNo { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Product_Group { get; set; }
        public string FreeText { get; set; }
        public Nullable<long> obsoletecode { get; set; }
    }
}
