//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_demo_invoices
    {
        public Nullable<int> SalesOrder { get; set; }
        public Nullable<long> NewOrderNo { get; set; }
        public Nullable<int> PickingSlipNo { get; set; }
        public Nullable<long> NewPickSlipNo { get; set; }
        public int InvoiceNo { get; set; }
        public Nullable<long> NewInvoiceNo { get; set; }
    }
}
