//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_visexp01_address_map_bak
    {
        public string Companyid { get; set; }
        public string BusinessId { get; set; }
        public string OnlineUserId { get; set; }
        public string Employeeid { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string MapUser { get; set; }
    }
}
