//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class e4kmaximusdbEntities : DbContext
    {
        public e4kmaximusdbEntities()
            : base("name=e4kmaximusdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<hr_emplo_ve> hr_emplo_ve { get; set; }
        public DbSet<hr_tremot02> hr_tremot02 { get; set; }
        public DbSet<hr_tremot02_derbyf> hr_tremot02_derbyf { get; set; }
        public DbSet<hr_tremot02_derbym> hr_tremot02_derbym { get; set; }
        public DbSet<hr_tremot02_langleyf> hr_tremot02_langleyf { get; set; }
        public DbSet<hr_tremot02_langleym> hr_tremot02_langleym { get; set; }
        public DbSet<hr_tremot02_nottmf> hr_tremot02_nottmf { get; set; }
        public DbSet<hr_tremot02_nottmm> hr_tremot02_nottmm { get; set; }
        public DbSet<hr_tremot02_suttonf> hr_tremot02_suttonf { get; set; }
        public DbSet<hr_tremot02_suttonm> hr_tremot02_suttonm { get; set; }
        public DbSet<hr_tsb_reldates> hr_tsb_reldates { get; set; }
        public DbSet<hr_tsb_release> hr_tsb_release { get; set; }
        public DbSet<my_aspnet_applications> my_aspnet_applications { get; set; }
        public DbSet<my_aspnet_membership> my_aspnet_membership { get; set; }
        public DbSet<my_aspnet_paths> my_aspnet_paths { get; set; }
        public DbSet<my_aspnet_personalizationallusers> my_aspnet_personalizationallusers { get; set; }
        public DbSet<my_aspnet_personalizationperuser> my_aspnet_personalizationperuser { get; set; }
        public DbSet<my_aspnet_profiles> my_aspnet_profiles { get; set; }
        public DbSet<my_aspnet_roles> my_aspnet_roles { get; set; }
        public DbSet<my_aspnet_sessioncleanup> my_aspnet_sessioncleanup { get; set; }
        public DbSet<my_aspnet_sessions> my_aspnet_sessions { get; set; }
        public DbSet<my_aspnet_sitemap> my_aspnet_sitemap { get; set; }
        public DbSet<my_aspnet_users> my_aspnet_users { get; set; }
        public DbSet<my_aspnet_usersinroles> my_aspnet_usersinroles { get; set; }
        public DbSet<tbl_employee_s27_hr> tbl_employee_s27_hr { get; set; }
        public DbSet<tblacc_vatcodes> tblacc_vatcodes { get; set; }
        public DbSet<tblaccemp_budget> tblaccemp_budget { get; set; }
        public DbSet<tblaccemp_budgetcard> tblaccemp_budgetcard { get; set; }
        public DbSet<tblaccemp_departments> tblaccemp_departments { get; set; }
        public DbSet<tblaccemp_employee> tblaccemp_employee { get; set; }
        public DbSet<tblaccemp_employee_rollout> tblaccemp_employee_rollout { get; set; }
        public DbSet<tblaccemp_points> tblaccemp_points { get; set; }
        public DbSet<tblaccemp_pointscard> tblaccemp_pointscard { get; set; }
        public DbSet<tblaccemp_rollout_names> tblaccemp_rollout_names { get; set; }
        public DbSet<tblaccemp_rollout_ucode_ref> tblaccemp_rollout_ucode_ref { get; set; }
        public DbSet<tblaccemp_stockcard> tblaccemp_stockcard { get; set; }
        public DbSet<tblaccemp_ucode_reasons> tblaccemp_ucode_reasons { get; set; }
        public DbSet<tblaccemp_ucodes> tblaccemp_ucodes { get; set; }
        public DbSet<tblaccemp_ucodes_desc> tblaccemp_ucodes_desc { get; set; }
        public DbSet<tblaccemp_ucodes_dimension> tblaccemp_ucodes_dimension { get; set; }
        public DbSet<tblaccemp_ucodes_hours> tblaccemp_ucodes_hours { get; set; }
        public DbSet<tblaccemp_ucodesemployees> tblaccemp_ucodesemployees { get; set; }
        public DbSet<tblaccesslevel> tblaccesslevels { get; set; }
        public DbSet<tbladmin> tbladmins { get; set; }
        public DbSet<tblasm_assemblydetail> tblasm_assemblydetail { get; set; }
        public DbSet<tblasm_assemblyheader> tblasm_assemblyheader { get; set; }
        public DbSet<tblbus_account> tblbus_account { get; set; }
        public DbSet<tblbus_address> tblbus_address { get; set; }
        public DbSet<tblbus_address_copy> tblbus_address_copy { get; set; }
        public DbSet<tblbus_addresstype_ref> tblbus_addresstype_ref { get; set; }
        public DbSet<tblbus_addresstypes> tblbus_addresstypes { get; set; }
        public DbSet<tblbus_business> tblbus_business { get; set; }
        public DbSet<tblbus_business_types> tblbus_business_types { get; set; }
        public DbSet<tblbus_contact> tblbus_contact { get; set; }
        public DbSet<tblbus_contact_ref> tblbus_contact_ref { get; set; }
        public DbSet<tblbus_countrycodes> tblbus_countrycodes { get; set; }
        public DbSet<tblbus_groups_ref> tblbus_groups_ref { get; set; }
        public DbSet<tblbus_online_orderref_nominal> tblbus_online_orderref_nominal { get; set; }
        public DbSet<tblbus_settings> tblbus_settings { get; set; }
        public DbSet<tblbus_settings_copy> tblbus_settings_copy { get; set; }
        public DbSet<tblbus_setvalues> tblbus_setvalues { get; set; }
        public DbSet<tblbus_styles> tblbus_styles { get; set; }
        public DbSet<tblchildmenu> tblchildmenus { get; set; }
        public DbSet<tblchildmenu_new> tblchildmenu_new { get; set; }
        public DbSet<tblchildmenu_newlayout> tblchildmenu_newlayout { get; set; }
        public DbSet<tblcmp_defaults> tblcmp_defaults { get; set; }
        public DbSet<tblcompany> tblcompanies { get; set; }
        public DbSet<tblcontent_lang> tblcontent_lang { get; set; }
        public DbSet<tblfsk_class> tblfsk_class { get; set; }
        public DbSet<tblfsk_features> tblfsk_features { get; set; }
        public DbSet<tblfsk_price> tblfsk_price { get; set; }
        public DbSet<tblfsk_seasons> tblfsk_seasons { get; set; }
        public DbSet<tblfsk_settings> tblfsk_settings { get; set; }
        public DbSet<tblfsk_setvalues> tblfsk_setvalues { get; set; }
        public DbSet<tblfsk_style> tblfsk_style { get; set; }
        public DbSet<tblfsk_style_colour> tblfsk_style_colour { get; set; }
        public DbSet<tblfsk_style_colour_size> tblfsk_style_colour_size { get; set; }
        public DbSet<tblfsk_style_colour_size_obsolete> tblfsk_style_colour_size_obsolete { get; set; }
        public DbSet<tblfsk_style_commoditycode> tblfsk_style_commoditycode { get; set; }
        public DbSet<tblfsk_style_customers> tblfsk_style_customers { get; set; }
        public DbSet<tblfsk_style_freetext> tblfsk_style_freetext { get; set; }
        public DbSet<tblfsk_style_freetext_copy> tblfsk_style_freetext_copy { get; set; }
        public DbSet<tblfsk_style_groups> tblfsk_style_groups { get; set; }
        public DbSet<tblfsk_style_groups_sub> tblfsk_style_groups_sub { get; set; }
        public DbSet<tblfsk_style_locations> tblfsk_style_locations { get; set; }
        public DbSet<tblfsk_style_reps> tblfsk_style_reps { get; set; }
        public DbSet<tblfsk_style_sizes> tblfsk_style_sizes { get; set; }
        public DbSet<tblfsk_style_sizes_prices> tblfsk_style_sizes_prices { get; set; }
        public DbSet<tblfsk_style_stock_levels> tblfsk_style_stock_levels { get; set; }
        public DbSet<tblfsk_style_stockingtypes> tblfsk_style_stockingtypes { get; set; }
        public DbSet<tblfsk_style_typeofissue> tblfsk_style_typeofissue { get; set; }
        public DbSet<tblfsk_unitofmeasure> tblfsk_unitofmeasure { get; set; }
        public DbSet<tblfsk_unitofmeasure_customer> tblfsk_unitofmeasure_customer { get; set; }
        public DbSet<tblfsk_unitofmeasureconversion> tblfsk_unitofmeasureconversion { get; set; }
        public DbSet<tblfstk_feature> tblfstk_feature { get; set; }
        public DbSet<tblfstk_featureoption_type> tblfstk_featureoption_type { get; set; }
        public DbSet<tblgen_autonumbers> tblgen_autonumbers { get; set; }
        public DbSet<tblgen_log> tblgen_log { get; set; }
        public DbSet<tblgen_nextno> tblgen_nextno { get; set; }
        public DbSet<tblgen_parameters> tblgen_parameters { get; set; }
        public DbSet<tblgen_user_defaults> tblgen_user_defaults { get; set; }
        public DbSet<tblgen_user_parameters> tblgen_user_parameters { get; set; }
        public DbSet<tblgen_users> tblgen_users { get; set; }
        public DbSet<tbllanguage> tbllanguages { get; set; }
        public DbSet<tblonline_emp_address_copy> tblonline_emp_address_copy { get; set; }
        public DbSet<tblonline_holidays> tblonline_holidays { get; set; }
        public DbSet<tblonline_rolloutorders_config> tblonline_rolloutorders_config { get; set; }
        public DbSet<tblonline_rolloutorders_reqstatus> tblonline_rolloutorders_reqstatus { get; set; }
        public DbSet<tblonline_userid_employee> tblonline_userid_employee { get; set; }
        public DbSet<tblonline_userid_favourites> tblonline_userid_favourites { get; set; }
        public DbSet<tblonlinesop_carriage> tblonlinesop_carriage { get; set; }
        public DbSet<tblonlinesop_sitecode> tblonlinesop_sitecode { get; set; }
        public DbSet<tblparentmenu> tblparentmenus { get; set; }
        public DbSet<tblparentmenu_new> tblparentmenu_new { get; set; }
        public DbSet<tblparentmenu_newlayout> tblparentmenu_newlayout { get; set; }
        public DbSet<tblpayment_gateways> tblpayment_gateways { get; set; }
        public DbSet<tblpayment_trans> tblpayment_trans { get; set; }
        public DbSet<tblpermission_controls> tblpermission_controls { get; set; }
        public DbSet<tblpermission_controls_category> tblpermission_controls_category { get; set; }
        public DbSet<tblpermission_settings> tblpermission_settings { get; set; }
        public DbSet<tblpermission_settings_users> tblpermission_settings_users { get; set; }
        public DbSet<tblpermission_users_allow> tblpermission_users_allow { get; set; }
        public DbSet<tblpermission_users_deny> tblpermission_users_deny { get; set; }
        public DbSet<tblquestionanswer> tblquestionanswers { get; set; }
        public DbSet<tblrep_kams> tblrep_kams { get; set; }
        public DbSet<tblsop_carrier> tblsop_carrier { get; set; }
        public DbSet<tblsop_courier_information> tblsop_courier_information { get; set; }
        public DbSet<tblsop_customer_ref> tblsop_customer_ref { get; set; }
        public DbSet<tblsop_customerorder_template> tblsop_customerorder_template { get; set; }
        public DbSet<tblsop_customerorder_template_costcentre> tblsop_customerorder_template_costcentre { get; set; }
        public DbSet<tblsop_customerorder_template_img> tblsop_customerorder_template_img { get; set; }
        public DbSet<tblsop_customerorder_template_ucodes> tblsop_customerorder_template_ucodes { get; set; }
        public DbSet<tblsop_despatch_confirm> tblsop_despatch_confirm { get; set; }
        public DbSet<tblsop_despatch_status> tblsop_despatch_status { get; set; }
        public DbSet<tblsop_download_fields> tblsop_download_fields { get; set; }
        public DbSet<tblsop_invoice_detail> tblsop_invoice_detail { get; set; }
        public DbSet<tblsop_invoice_header> tblsop_invoice_header { get; set; }
        public DbSet<tblsop_manpackorders> tblsop_manpackorders { get; set; }
        public DbSet<tblsop_manpackreturns> tblsop_manpackreturns { get; set; }
        public DbSet<tblsop_pickingslip_detail> tblsop_pickingslip_detail { get; set; }
        public DbSet<tblsop_pickingslip_header> tblsop_pickingslip_header { get; set; }
        public DbSet<tblsop_reasoncodes> tblsop_reasoncodes { get; set; }
        public DbSet<tblsop_reasons> tblsop_reasons { get; set; }
        public DbSet<tblsop_return_reasoncodes> tblsop_return_reasoncodes { get; set; }
        public DbSet<tblsop_return_reasoncodes_customer> tblsop_return_reasoncodes_customer { get; set; }
        public DbSet<tblsop_salesorder_approved> tblsop_salesorder_approved { get; set; }
        public DbSet<tblsop_salesorder_detail> tblsop_salesorder_detail { get; set; }
        public DbSet<tblsop_salesorder_detail_offline> tblsop_salesorder_detail_offline { get; set; }
        public DbSet<tblsop_salesorder_detail_tremot02> tblsop_salesorder_detail_tremot02 { get; set; }
        public DbSet<tblsop_salesorder_header> tblsop_salesorder_header { get; set; }
        public DbSet<tblsop_salesorder_header_offline> tblsop_salesorder_header_offline { get; set; }
        public DbSet<tblsop_salesorder_header_tremot02> tblsop_salesorder_header_tremot02 { get; set; }
        public DbSet<tblsqlstring> tblsqlstrings { get; set; }
        public DbSet<tblupdate_status_three> tblupdate_status_three { get; set; }
        public DbSet<tbluser> tblusers { get; set; }
        public DbSet<tblwho_warehouses> tblwho_warehouses { get; set; }
        public DbSet<tblwho_warehousesx> tblwho_warehousesx { get; set; }
        public DbSet<xml_salesorder_detail> xml_salesorder_detail { get; set; }
        public DbSet<xml_salesorder_header> xml_salesorder_header { get; set; }
        public DbSet<bak_tblaccemp_employee_tsb> bak_tblaccemp_employee_tsb { get; set; }
        public DbSet<copy_tblusers> copy_tblusers { get; set; }
        public DbSet<hr_tsb_min_orderdate> hr_tsb_min_orderdate { get; set; }
        public DbSet<hr_tsb_tblaccemp_ucodesemployees> hr_tsb_tblaccemp_ucodesemployees { get; set; }
        public DbSet<hr_visexp01_address_map_bak> hr_visexp01_address_map_bak { get; set; }
        public DbSet<rollout_order_detail_tsb> rollout_order_detail_tsb { get; set; }
        public DbSet<rollout_order_header_address_tsb> rollout_order_header_address_tsb { get; set; }
        public DbSet<rollout_order_header_tsb> rollout_order_header_tsb { get; set; }
        public DbSet<stockcard_tsb_rollout> stockcard_tsb_rollout { get; set; }
        public DbSet<tblaccemp_style_staticqty> tblaccemp_style_staticqty { get; set; }
        public DbSet<tblbus_address_s27> tblbus_address_s27 { get; set; }
        public DbSet<tblbus_contact_s27> tblbus_contact_s27 { get; set; }
        public DbSet<tblonline_userid_employee_s27> tblonline_userid_employee_s27 { get; set; }
        public DbSet<tblonlinesop_backorders> tblonlinesop_backorders { get; set; }
        public DbSet<tblsop_salesorder_detail_bk> tblsop_salesorder_detail_bk { get; set; }
        public DbSet<tblsop_salesorder_detail_console> tblsop_salesorder_detail_console { get; set; }
        public DbSet<tblsop_salesorder_header_bk> tblsop_salesorder_header_bk { get; set; }
        public DbSet<tblsop_salesorder_header_console> tblsop_salesorder_header_console { get; set; }
        public DbSet<tblupload_orderdetail> tblupload_orderdetail { get; set; }
        public DbSet<tblupload_orderheader> tblupload_orderheader { get; set; }
        public DbSet<ucode_employee_rollout_tsb> ucode_employee_rollout_tsb { get; set; }
        public DbSet<getallassembly> getallassemblies { get; set; }
        public DbSet<getcolour> getcolours { get; set; }
        public DbSet<getcustassembly> getcustassemblies { get; set; }
        public DbSet<getproductslist> getproductslists { get; set; }
        public DbSet<getsize> getsizes { get; set; }
        public DbSet<getstylesview> getstylesviews { get; set; }
        public DbSet<style_dimfitalloc_caption> style_dimfitalloc_caption { get; set; }
        public DbSet<styleby_freetextview> styleby_freetextview { get; set; }
    
        public virtual ObjectResult<getColors_prod_Result> getColors_prod(string style)
        {
            var styleParameter = style != null ?
                new ObjectParameter("style", style) :
                new ObjectParameter("style", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getColors_prod_Result>("getColors_prod", styleParameter);
        }
    }
}
