//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rollout_order_header_address_tsb
    {
        public string EmployeeID { get; set; }
        public string BusinessID { get; set; }
        public string OnlineUserID { get; set; }
        public string AddressID { get; set; }
        public string Description { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string Town { get; set; }
        public string Postcode { get; set; }
    }
}
