//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblaccemp_stylepoints
    {
        public string CompanyID { get; set; }
        public string BusinessID { get; set; }
        public string UcodeID { get; set; }
        public string StyleID { get; set; }
        public string ColourID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> MandatoryQty { get; set; }
        public Nullable<int> MinPts { get; set; }
        public Nullable<int> MaxPts { get; set; }
    }
}
