//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblaccemp_stockcard
    {
        public string CompanyID { get; set; }
        public string BusinessID { get; set; }
        public string EmployeeID { get; set; }
        public string StyleID { get; set; }
        public string ColourID { get; set; }
        public short Year { get; set; }
        public Nullable<int> SOQty { get; set; }
        public Nullable<int> PickQty { get; set; }
        public Nullable<int> InvQty { get; set; }
        public Nullable<int> TotalIssues { get; set; }
        public Nullable<System.DateTime> FirstIssueDate { get; set; }
        public Nullable<System.DateTime> StartIssueDate { get; set; }
        public Nullable<System.DateTime> LastIssueDate { get; set; }
    }
}
