//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbladmin
    {
        public string UserID { get; set; }
        public string Pwd { get; set; }
        public string AccessGroup { get; set; }
        public Nullable<sbyte> CanUpload { get; set; }
    }
}
