//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbus_contact
    {
        public int ID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<int> ContactType_ID { get; set; }
        public string Value { get; set; }
    }
}
