//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbus_business_types
    {
        public string BusTypeID { get; set; }
        public string BusType_Name { get; set; }
        public string BusType_Control_Table { get; set; }
        public string BusType_Tran_Table { get; set; }
        public string BusType_Hist_Table { get; set; }
        public string BusType_Nominal_Control { get; set; }
        public string BusType_VAT_Control { get; set; }
    }
}
