//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbus_countrycodes
    {
        public string CompanyID { get; set; }
        public int CountryID { get; set; }
        public string Country { get; set; }
        public string Currency_Name { get; set; }
        public string Currency_Symbol { get; set; }
        public Nullable<double> Currency_Exchange_Rate { get; set; }
        public string Member { get; set; }
        public string ISOCode { get; set; }
    }
}
