//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbus_business
    {
        public string CompanyID { get; set; }
        public string BusinessID { get; set; }
        public string BusType { get; set; }
        public string Name { get; set; }
        public Nullable<int> Country_Currency { get; set; }
        public sbyte Live { get; set; }
        public Nullable<int> AnalysisCodeID { get; set; }
        public string Default_Nominal { get; set; }
        public string Factoring_No { get; set; }
        public string Comments { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string CoupleID { get; set; }
        public sbyte IsExtract { get; set; }
    }
}
