//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcontent_lang
    {
        public string BusinessID { get; set; }
        public string LangID { get; set; }
        public string content { get; set; }
        public Nullable<sbyte> Enable { get; set; }
    }
}
