//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfsk_style_sizes_prices
    {
        public string CompanyID { get; set; }
        public string BusinessId { get; set; }
        public string StyleID { get; set; }
        public string SizeID { get; set; }
        public int PriceID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int Country_Currency { get; set; }
    }
}
