//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfsk_style_customers
    {
        public string CompanyID { get; set; }
        public string CustomerID { get; set; }
        public string StyleID { get; set; }
        public string CustomerProd_code { get; set; }
        public Nullable<int> Customer_price { get; set; }
        public Nullable<int> CustomerSeq { get; set; }
    }
}
