//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblgen_users
    {
        public string UserID { get; set; }
        public string Password { get; set; }
        public Nullable<int> AccessID { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string Description { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public Nullable<System.DateTime> Last_Logon { get; set; }
        public bool LoggedOn { get; set; }
        public bool Locked { get; set; }
        public bool CanBeChanged { get; set; }
        public bool CanBeDeleted { get; set; }
        public string IP_Address { get; set; }
        public string PasswordPayment { get; set; }
        public string CompanyID { get; set; }
        public string WarehouseID { get; set; }
        public string EmailID { get; set; }
    }
}
