//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblonlinesop_sitecode
    {
        public string CompanyID { get; set; }
        public string BusinessID { get; set; }
        public string SiteCode { get; set; }
        public string SiteName { get; set; }
        public Nullable<long> AddressID { get; set; }
    }
}
