//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblonline_rolloutorders_config
    {
        public string CompanyID { get; set; }
        public string BusinessID { get; set; }
        public string RolloutName { get; set; }
        public string DefaultEmpID { get; set; }
        public Nullable<int> IsAssembly { get; set; }
        public Nullable<int> IsReq { get; set; }
        public Nullable<int> IsAutoconfirm { get; set; }
        public Nullable<int> IsEmployeeCreate { get; set; }
        public Nullable<int> IsAddressCreate { get; set; }
        public Nullable<int> IsEmpStockCard { get; set; }
        public Nullable<int> IsRolloutEmployee { get; set; }
        public string ErrorMailTo { get; set; }
        public string OrderMailTo { get; set; }
        public Nullable<int> SOPDETAIL5Field { get; set; }
        public Nullable<bool> IsPINNO { get; set; }
    }
}
