//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpayment_trans
    {
        public int ID { get; set; }
        public string RefNo { get; set; }
        public string txn_id { get; set; }
        public Nullable<System.DateTime> txn_date { get; set; }
        public string txn_status { get; set; }
        public Nullable<System.DateTime> rsp_date { get; set; }
        public string Reasons { get; set; }
        public string rsp_status { get; set; }
        public Nullable<decimal> txn_amt { get; set; }
        public string txn_Ip { get; set; }
        public string OrderNos { get; set; }
        public Nullable<sbyte> IsPackOrder { get; set; }
        public string EncrypteData { get; set; }
        public Nullable<int> GatewayID { get; set; }
        public string RefNoSP { get; set; }
    }
}
