//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsop_manpackreturns
    {
        public string CompanyID { get; set; }
        public long ManPackNo { get; set; }
        public long OrderNo { get; set; }
        public string CustID { get; set; }
        public Nullable<System.DateTime> ManpackDate { get; set; }
        public string OnlineUserID { get; set; }
        public Nullable<sbyte> OnlineConfirm { get; set; }
        public Nullable<sbyte> OnlineProcessed { get; set; }
        public Nullable<System.DateTime> OnlineConfirmDate { get; set; }
        public string OnlineConfirmedBy { get; set; }
        public Nullable<System.DateTime> OnlineProcessedDate { get; set; }
        public string OnlineProcessedBy { get; set; }
    }
}
