//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsop_courier_information
    {
        public string CompanyID { get; set; }
        public string CustID { get; set; }
        public string DelDesc { get; set; }
        public long OrderNo { get; set; }
        public int DeliveryNote { get; set; }
        public string CourierRef { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DespatchDate { get; set; }
        public Nullable<int> Despatched { get; set; }
        public string PSDetailInfo { get; set; }
        public string CarrierID { get; set; }
    }
}
