//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsop_customerorder_template_costcentre
    {
        public string CompanyID { get; set; }
        public string BusinessID { get; set; }
        public long CodeID { get; set; }
        public string ProjectCode { get; set; }
        public string SiteName { get; set; }
        public string TemplateCode { get; set; }
        public string Uniformcode { get; set; }
    }
}
