//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsop_salesorder_detail_offline
    {
        public string CompanyID { get; set; }
        public string Warehouseid { get; set; }
        public int OrderNo { get; set; }
        public int LineNo { get; set; }
        public Nullable<short> LineType { get; set; }
        public string StyleID { get; set; }
        public string ColourID { get; set; }
        public string SizeID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> OrdQty { get; set; }
        public Nullable<int> AllQty { get; set; }
        public Nullable<int> InvQty { get; set; }
        public Nullable<int> DespQty { get; set; }
        public Nullable<double> CommissionRate { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<System.DateTime> Deliverydate { get; set; }
        public Nullable<short> VatCode { get; set; }
        public Nullable<short> NomCode { get; set; }
        public sbyte PartShip { get; set; }
        public Nullable<double> LineNoRef { get; set; }
        public Nullable<double> Currency_Exchange_Rate { get; set; }
        public string StyleIDref { get; set; }
        public string FreeText { get; set; }
        public Nullable<int> RepID { get; set; }
        public Nullable<double> RepRate { get; set; }
        public Nullable<int> KamID { get; set; }
        public Nullable<double> KAMRate { get; set; }
        public Nullable<int> IssueUOM { get; set; }
        public Nullable<double> IssueQty { get; set; }
        public Nullable<int> StockingUOM { get; set; }
        public Nullable<int> OriginalOrderNo { get; set; }
        public Nullable<int> OriginalLineNo { get; set; }
        public string SOPDETAIL1 { get; set; }
        public string SOPDETAIL2 { get; set; }
        public string SOPDETAIL3 { get; set; }
        public string SOPDETAIL4 { get; set; }
        public string SOPDETAIL5 { get; set; }
        public Nullable<int> JobSheetNo { get; set; }
        public Nullable<int> JobSheetLineNo { get; set; }
        public Nullable<int> AssemblyID { get; set; }
        public Nullable<int> AsmLineNo { get; set; }
        public Nullable<int> ReasonCode { get; set; }
        public Nullable<int> ReturnOrderNo { get; set; }
        public Nullable<int> ReturnLineNo { get; set; }
    }
}
