//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_privateorder_pendings
    {
        public string CompanyID { get; set; }
        public string CustID { get; set; }
        public long OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<double> TotalGoods { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<double> OrderGoods { get; set; }
        public string txn_id { get; set; }
        public string txn_Ip { get; set; }
        public Nullable<System.DateTime> rsp_date { get; set; }
        public string rsp_status { get; set; }
        public string GatewayImg { get; set; }
        public string GatewayName { get; set; }
        public int SeqNo { get; set; }
    }
}
