//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_manpack
    {
        public long ManPackNo { get; set; }
        public Nullable<System.DateTime> ManpackDate { get; set; }
        public Nullable<double> TotalGoods { get; set; }
        public Nullable<double> OrderGoods { get; set; }
        public string CustID { get; set; }
        public string CompanyID { get; set; }
        public string OnlineUserID { get; set; }
    }
}
