//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_unmatchedcolourwithorgcolour
    {
        public string PinNo { get; set; }
        public string UCodeId { get; set; }
        public string CustID { get; set; }
        public long OrderNo { get; set; }
        public Nullable<long> ReturnOrderNo { get; set; }
        public Nullable<long> OriginalOrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string StyleID { get; set; }
        public string ColourID { get; set; }
        public string SizeID { get; set; }
        public Nullable<long> OrdQty { get; set; }
        public string OrgColourID { get; set; }
    }
}
